Fix bug in small allocator in case of small slab_alloc_factor
tarantool/small pull request #27
Opened 2020-11-05 11:31 UTC by mechanik20051988

In case of small slab_alloc_factor, factor_pool_cache
array have no enought place. This caused us to use a pool
with incorrect object sizes. This patch changed allocator
behavior, now we allocate pools on the stage of allocator
creation. Also we search for the desired pool using binary
search in an ordered array, which is generally faster
than searching in a red-black tree.

Closes #5216

2020-11-09 10:29 UTC, Gerold103 commented
I didn't look at the patch carefully, but generally we split bugfix and optimizations into separate commits. From this commit message I see that you fixed the bug and did an optimization. Can you split it?

2020-11-09 16:53 UTC, mechanik20051988 commented
> I didn't look at the patch carefully, but generally we split bugfix and optimizations into separate commits. From this commit message I see that you fixed the bug and did an optimization. Can you split it?

Ok! Now I am testing the performance of my changes, if it turns out that it is lower than it was before, then I will only fix the bug. If the performance is better, I will split the patch into several parts.

2020-12-17 04:46 UTC, alyapunov requested changes

2020-12-17 14:59 UTC, alyapunov approved these changes
LGTM except commit about CentOS6 built. It's not relevant to this task and must be linked to another issue.

2020-12-28 12:40 UTC, Gerold103 approved these changes

2021-02-10 15:06 UTC, closed without merging